
package cliente.conversor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParseIntegerService", targetNamespace = "http://webService/", wsdlLocation = "http://localhost:9999/ws/parseInteger?wsdl")
public class ParseIntegerService
    extends Service
{

    private final static URL PARSEINTEGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARSEINTEGERSERVICE_EXCEPTION;
    private final static QName PARSEINTEGERSERVICE_QNAME = new QName("http://webService/", "ParseIntegerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/parseInteger?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARSEINTEGERSERVICE_WSDL_LOCATION = url;
        PARSEINTEGERSERVICE_EXCEPTION = e;
    }

    public ParseIntegerService() {
        super(__getWsdlLocation(), PARSEINTEGERSERVICE_QNAME);
    }

    public ParseIntegerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARSEINTEGERSERVICE_QNAME, features);
    }

    public ParseIntegerService(URL wsdlLocation) {
        super(wsdlLocation, PARSEINTEGERSERVICE_QNAME);
    }

    public ParseIntegerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARSEINTEGERSERVICE_QNAME, features);
    }

    public ParseIntegerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParseIntegerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IParseInteger
     */
    @WebEndpoint(name = "ParseIntegerPort")
    public IParseInteger getParseIntegerPort() {
        return super.getPort(new QName("http://webService/", "ParseIntegerPort"), IParseInteger.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IParseInteger
     */
    @WebEndpoint(name = "ParseIntegerPort")
    public IParseInteger getParseIntegerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "ParseIntegerPort"), IParseInteger.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARSEINTEGERSERVICE_EXCEPTION!= null) {
            throw PARSEINTEGERSERVICE_EXCEPTION;
        }
        return PARSEINTEGERSERVICE_WSDL_LOCATION;
    }

}
